name: Run tests and linters

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2024.11.14'

      - uses: DeLaGuardo/setup-clojure@13.1
        with:
          tools-deps: '1.12.0.1495'

      - name: Run checks
        run: make checks

      - name: Run tests
        run: make test
