name: Run tests and linters

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2022.09.08'

      - uses: DeLaGuardo/setup-clojure@9.5
        with:
          tools-deps: '1.11.1.1165'

      - name: Run checks
        run: make checks

      - name: Run tests
        run: make test
