name: Run tests and linters

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2023.09.07'

      - uses: DeLaGuardo/setup-clojure@12.1
        with:
          tools-deps: '1.11.1.1413'

      - name: Run checks
        run: make checks

      - name: Run tests
        run: make test
