name: Run tests and linters

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2021.12.19'
    
    - uses: DeLaGuardo/setup-clojure@3.7
      with:
        tools-deps: '1.10.3.1058'

    - name: Run checks
      run: make checks

    - name: Run tests
      run: make test
