name: Create release on push to master

on:
  pull_request:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2022.04.25'

      - uses: DeLaGuardo/setup-clojure@5.1
        with:
          tools-deps: '1.11.1.1113'

      - name: Make archive with issues
        run: make release

      - name: get shortsha
        id: vars
        run: |
          echo ::set-output name=sha_short::$(git rev-parse --short=6 ${{ github.sha }})

      - name: Release issues
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: ${{ steps.vars.outputs.sha_short }}
          prerelease: false
          title: 'Release'
          files: ./issues.tar.gz
